# Generated by Django 4.1.2 on 2022-10-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qoutes', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='now',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
